// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Optimus.Infrastructure.Data;

#nullable disable

namespace Optimus.Infrastructure.Data.Migrations
{
    [DbContext(typeof(OptimusDbContext))]
    [Migration("20240518200102_SeedCustomersDataWithCreatedAt")]
    partial class SeedCustomersDataWithCreatedAt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Optimus.Domain.Entities.Customers.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("address");

                    b.Property<string>("Comments")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("comments");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cpf");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone");

                    b.HasKey("Id")
                        .HasName("pk_customers");

                    b.HasIndex("Cpf")
                        .IsUnique()
                        .HasDatabaseName("ix_customers_cpf");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_customers_email");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_customers_name");

                    b.ToTable("customers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("54d539a0-5c79-4f00-a132-4224a4955889"),
                            Address = "57113 Eduardo Marginal, Rio de Janeiro, Ilha do Natal",
                            Comments = "Ratione libero laudantium nulla asperiores praesentium voluptas aut cupiditate id.\nEnim vero illo veritatis sed consequatur facilis ut sit ut.\nIpsum placeat aut quos qui sit.",
                            Cpf = "107.229.157-64",
                            Email = "Celia_Costa@bol.com.br",
                            Name = "Célia Costa",
                            Phone = "+55 (43) 9422-0740"
                        },
                        new
                        {
                            Id = new Guid("5c56fada-527e-425e-9e64-a86a7a594605"),
                            Address = "46647 Washington Rodovia, Ananindeua, México",
                            Comments = "Ut omnis fuga.\nEum reprehenderit veritatis quae.\nDistinctio amet vel et ab consequatur.\nEst aut dolorem esse.\nExplicabo cupiditate harum sapiente velit similique est provident vel omnis.\nInventore sit rerum mollitia iste.",
                            Cpf = "275.245.255-16",
                            Email = "Isabel80@live.com",
                            Name = "Isabel Carvalho",
                            Phone = "+55 (59) 4196-2468"
                        },
                        new
                        {
                            Id = new Guid("69351cc3-daf4-4995-8e4d-bcdce845c784"),
                            Address = "267 Souza Rodovia, Sumaré, República da África Central",
                            Comments = "provident",
                            Cpf = "201.432.508-17",
                            Email = "Fabio_Albuquerque57@hotmail.com",
                            Name = "Fábio Albuquerque",
                            Phone = "(01) 41504-8249"
                        },
                        new
                        {
                            Id = new Guid("eb3b5213-638e-478d-8ff7-25f46f57315d"),
                            Address = "742 Oliveira Rua, Goiânia, Eslovênia",
                            Comments = "Ut quia ut laudantium et.\nVoluptatibus id totam illo aut placeat.\nQuia suscipit provident nam ut magnam eligendi blanditiis dolorum.\nEum necessitatibus animi voluptatem dolorem rerum rem qui officiis.\nVoluptatum a itaque magni consectetur.\nEarum animi ratione magni eius repellendus excepturi.",
                            Cpf = "177.614.214-47",
                            Email = "Isis54@hotmail.com",
                            Name = "Isis Souza",
                            Phone = "+55 (76) 8399-1465"
                        },
                        new
                        {
                            Id = new Guid("9cc9d4bf-3ce0-460c-818a-9b0b972f70c0"),
                            Address = "3546 Macedo Rua, Serra, Sao Tomé e Príncipe",
                            Comments = "Molestiae fuga eveniet sed et.",
                            Cpf = "775.084.905-09",
                            Email = "DaviLucca_Franco@hotmail.com",
                            Name = "Davi Lucca Franco",
                            Phone = "+55 (34) 1967-2908"
                        });
                });

            modelBuilder.Entity("Optimus.Domain.Entities.Products.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Comments")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("comments");

                    b.Property<decimal>("CostPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("cost_price");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("QuantityInStock")
                        .HasColumnType("integer")
                        .HasColumnName("quantity_in_stock");

                    b.Property<decimal>("SalePrice")
                        .HasColumnType("numeric")
                        .HasColumnName("sale_price");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_products_name");

                    b.ToTable("products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("0255639b-1e03-417a-b83f-2acb5ccdcec8"),
                            Comments = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            CostPrice = 7m,
                            CreatedAt = new DateTime(2024, 5, 18, 20, 1, 1, 659, DateTimeKind.Utc).AddTicks(4770),
                            Name = "Rústico Plástico Atum",
                            QuantityInStock = -2,
                            SalePrice = 14m
                        },
                        new
                        {
                            Id = new Guid("0365c970-0628-4a8d-b8d0-17b98d44b235"),
                            Comments = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            CostPrice = 9m,
                            CreatedAt = new DateTime(2024, 5, 18, 20, 1, 1, 663, DateTimeKind.Utc).AddTicks(229),
                            Name = "Incrível Algodão Sabonete",
                            QuantityInStock = 8,
                            SalePrice = 18m
                        },
                        new
                        {
                            Id = new Guid("371b243c-858e-4fc1-a8a5-384657e7a6b0"),
                            Comments = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            CostPrice = 6m,
                            CreatedAt = new DateTime(2024, 5, 18, 20, 1, 1, 668, DateTimeKind.Utc).AddTicks(1866),
                            Name = "Lustroso Granito Salgadinhos",
                            QuantityInStock = 10,
                            SalePrice = 12m
                        },
                        new
                        {
                            Id = new Guid("524a1ff0-933a-4d92-a040-3b3ea5ee03fe"),
                            Comments = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            CostPrice = 11m,
                            CreatedAt = new DateTime(2024, 5, 18, 20, 1, 1, 675, DateTimeKind.Utc).AddTicks(1011),
                            Name = "Inteligente Macio Mesa",
                            QuantityInStock = 8,
                            SalePrice = 22m
                        },
                        new
                        {
                            Id = new Guid("b1baa0bd-00d8-4bad-b607-35062136b84f"),
                            Comments = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            CostPrice = 13m,
                            CreatedAt = new DateTime(2024, 5, 18, 20, 1, 1, 681, DateTimeKind.Utc).AddTicks(7131),
                            Name = "Rústico Aço Calças",
                            QuantityInStock = 2,
                            SalePrice = 26m
                        },
                        new
                        {
                            Id = new Guid("1ea9310f-67d9-4cd6-a0e1-f5c7fe959826"),
                            Comments = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            CostPrice = 9m,
                            CreatedAt = new DateTime(2024, 5, 18, 20, 1, 1, 687, DateTimeKind.Utc).AddTicks(6706),
                            Name = "Licenciado Plástico Sapatos",
                            QuantityInStock = 1,
                            SalePrice = 18m
                        },
                        new
                        {
                            Id = new Guid("3c5d4924-9111-40bb-8ed7-d5838ce507af"),
                            Comments = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            CostPrice = 6m,
                            CreatedAt = new DateTime(2024, 5, 18, 20, 1, 1, 691, DateTimeKind.Utc).AddTicks(1821),
                            Name = "Licenciado Congelado Camiseta",
                            QuantityInStock = 1,
                            SalePrice = 12m
                        },
                        new
                        {
                            Id = new Guid("557e6cd5-56eb-4966-be5b-75c347738240"),
                            Comments = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            CostPrice = 11m,
                            CreatedAt = new DateTime(2024, 5, 18, 20, 1, 1, 694, DateTimeKind.Utc).AddTicks(7754),
                            Name = "Genérico Algodão Chapéu",
                            QuantityInStock = -2,
                            SalePrice = 22m
                        },
                        new
                        {
                            Id = new Guid("89626c1f-928a-4417-8ca3-7da555b5355a"),
                            Comments = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            CostPrice = 11m,
                            CreatedAt = new DateTime(2024, 5, 18, 20, 1, 1, 698, DateTimeKind.Utc).AddTicks(4440),
                            Name = "Refinado Metal Bicicleta",
                            QuantityInStock = 10,
                            SalePrice = 22m
                        },
                        new
                        {
                            Id = new Guid("3cb36462-24de-4f47-b35d-44b1393e233d"),
                            Comments = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            CostPrice = 11m,
                            CreatedAt = new DateTime(2024, 5, 18, 20, 1, 1, 702, DateTimeKind.Utc).AddTicks(2225),
                            Name = "Ergonômico Concreto Computador",
                            QuantityInStock = 7,
                            SalePrice = 22m
                        },
                        new
                        {
                            Id = new Guid("a1b119d1-98c3-49b0-b2e8-9880d17ea288"),
                            Comments = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            CostPrice = 9m,
                            CreatedAt = new DateTime(2024, 5, 18, 20, 1, 1, 709, DateTimeKind.Utc).AddTicks(2012),
                            Name = "Feito à mão Aço Queijo",
                            QuantityInStock = 1,
                            SalePrice = 18m
                        },
                        new
                        {
                            Id = new Guid("6856914a-254c-4d76-9c00-47562cc0b0af"),
                            Comments = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            CostPrice = 5m,
                            CreatedAt = new DateTime(2024, 5, 18, 20, 1, 1, 715, DateTimeKind.Utc).AddTicks(7156),
                            Name = "Lustroso Granito Teclado",
                            QuantityInStock = 3,
                            SalePrice = 10m
                        },
                        new
                        {
                            Id = new Guid("5a800f44-c266-4c98-b31e-a2990ee829fd"),
                            Comments = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            CostPrice = 7m,
                            CreatedAt = new DateTime(2024, 5, 18, 20, 1, 1, 722, DateTimeKind.Utc).AddTicks(8648),
                            Name = "Sem marca Macio Sabonete",
                            QuantityInStock = 3,
                            SalePrice = 14m
                        },
                        new
                        {
                            Id = new Guid("5ad25089-add4-4f69-abf4-e0a66d35ccf9"),
                            Comments = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            CostPrice = 8m,
                            CreatedAt = new DateTime(2024, 5, 18, 20, 1, 1, 729, DateTimeKind.Utc).AddTicks(4143),
                            Name = "Fantástico Algodão Bola",
                            QuantityInStock = -1,
                            SalePrice = 16m
                        },
                        new
                        {
                            Id = new Guid("c89151f5-a849-4e38-81e6-33d85933817a"),
                            Comments = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            CostPrice = 10m,
                            CreatedAt = new DateTime(2024, 5, 18, 20, 1, 1, 736, DateTimeKind.Utc).AddTicks(1945),
                            Name = "Refinado Algodão Pizza",
                            QuantityInStock = 1,
                            SalePrice = 20m
                        },
                        new
                        {
                            Id = new Guid("3be94411-e781-4b41-9809-56e3ec5d5bf4"),
                            Comments = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            CostPrice = 14m,
                            CreatedAt = new DateTime(2024, 5, 18, 20, 1, 1, 742, DateTimeKind.Utc).AddTicks(6239),
                            Name = "Ergonômico Fresco Atum",
                            QuantityInStock = 0,
                            SalePrice = 28m
                        },
                        new
                        {
                            Id = new Guid("a0c58cf2-c1d2-472a-b287-391809827b36"),
                            Comments = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            CostPrice = 12m,
                            CreatedAt = new DateTime(2024, 5, 18, 20, 1, 1, 749, DateTimeKind.Utc).AddTicks(2986),
                            Name = "Genérico Algodão Computador",
                            QuantityInStock = -2,
                            SalePrice = 24m
                        },
                        new
                        {
                            Id = new Guid("2be4a24f-941b-4987-9a6a-db2fa05c34ae"),
                            Comments = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            CostPrice = 8m,
                            CreatedAt = new DateTime(2024, 5, 18, 20, 1, 1, 766, DateTimeKind.Utc).AddTicks(760),
                            Name = "Feito à mão Madeira Queijo",
                            QuantityInStock = 1,
                            SalePrice = 16m
                        },
                        new
                        {
                            Id = new Guid("3f2b3c6e-fd66-440c-b8e8-31026ffa94ab"),
                            Comments = "The Football Is Good For Training And Recreational Purposes",
                            CostPrice = 12m,
                            CreatedAt = new DateTime(2024, 5, 18, 20, 1, 1, 772, DateTimeKind.Utc).AddTicks(3488),
                            Name = "Fantástico Concreto Carro",
                            QuantityInStock = 3,
                            SalePrice = 24m
                        },
                        new
                        {
                            Id = new Guid("8ed6cc17-ac57-4895-90ef-51636c2e6e5f"),
                            Comments = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            CostPrice = 8m,
                            CreatedAt = new DateTime(2024, 5, 18, 20, 1, 1, 778, DateTimeKind.Utc).AddTicks(8628),
                            Name = "Fantástico Granito Mesa",
                            QuantityInStock = 3,
                            SalePrice = 16m
                        });
                });

            modelBuilder.Entity("Optimus.Domain.Entities.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("InactivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("inactivated_at");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("password");

                    b.Property<int>("Profile")
                        .HasColumnType("integer")
                        .HasColumnName("profile");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a3607ec4-c0fc-41d4-9255-f02bf2e26468"),
                            CreatedAt = new DateTime(2024, 5, 18, 20, 1, 1, 653, DateTimeKind.Utc).AddTicks(6190),
                            Email = "admin@optimus.com",
                            Password = "7110eda4d09e062aa5e4a390b0a572ac0d2c0220",
                            Profile = 0
                        },
                        new
                        {
                            Id = new Guid("a5d68ac9-7736-41d3-a34f-77af8f27efb7"),
                            CreatedAt = new DateTime(2024, 5, 18, 20, 1, 1, 653, DateTimeKind.Utc).AddTicks(6193),
                            Email = "operador@optimus.com",
                            Password = "7110eda4d09e062aa5e4a390b0a572ac0d2c0220",
                            Profile = 1
                        },
                        new
                        {
                            Id = new Guid("119f93aa-0c62-4ddd-98fe-e2d76bc9016c"),
                            CreatedAt = new DateTime(2024, 5, 18, 20, 1, 1, 653, DateTimeKind.Utc).AddTicks(6181),
                            Email = "inativo@optimus.com",
                            InactivatedAt = new DateTime(2024, 5, 18, 20, 1, 1, 653, DateTimeKind.Utc).AddTicks(6184),
                            Password = "7110eda4d09e062aa5e4a390b0a572ac0d2c0220",
                            Profile = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
