// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Optimus.Infrastructure.Data;

#nullable disable

namespace Optimus.Infrastructure.Data.Migrations
{
    [DbContext(typeof(OptimusDbContext))]
    [Migration("20240518190346_CustomerEntityChanges")]
    partial class CustomerEntityChanges
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Optimus.Domain.Entities.Customers.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("address");

                    b.Property<string>("Comments")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("comments");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cpf");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone");

                    b.HasKey("Id")
                        .HasName("pk_customers");

                    b.HasIndex("Cpf")
                        .IsUnique()
                        .HasDatabaseName("ix_customers_cpf");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_customers_email");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_customers_name");

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("Optimus.Domain.Entities.Products.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Comments")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("comments");

                    b.Property<decimal>("CostPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("cost_price");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("QuantityInStock")
                        .HasColumnType("integer")
                        .HasColumnName("quantity_in_stock");

                    b.Property<decimal>("SalePrice")
                        .HasColumnType("numeric")
                        .HasColumnName("sale_price");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_products_name");

                    b.ToTable("products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a0ab7f67-ec4f-4ba2-82ae-8a97d6d04c1e"),
                            Comments = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            CostPrice = 13m,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Refinado Aço Bola",
                            QuantityInStock = 0,
                            SalePrice = 26m
                        },
                        new
                        {
                            Id = new Guid("a9fc0d0a-b8c9-4b99-81e8-9c04aa0f8e65"),
                            Comments = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            CostPrice = 5m,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Impressionante Plástico Sapatos",
                            QuantityInStock = 8,
                            SalePrice = 10m
                        },
                        new
                        {
                            Id = new Guid("6010cbb9-f598-4c58-af24-3c899d6c4aea"),
                            Comments = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            CostPrice = 9m,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Gostoso Algodão Salada",
                            QuantityInStock = 3,
                            SalePrice = 18m
                        },
                        new
                        {
                            Id = new Guid("899a2078-5229-4be1-9967-8c82e93e469e"),
                            Comments = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            CostPrice = 15m,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Licenciado Congelado Bola",
                            QuantityInStock = -1,
                            SalePrice = 30m
                        },
                        new
                        {
                            Id = new Guid("e9276f38-5214-4074-9dfe-ac30d3dad859"),
                            Comments = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            CostPrice = 7m,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Rústico Congelado Teclado",
                            QuantityInStock = 8,
                            SalePrice = 14m
                        },
                        new
                        {
                            Id = new Guid("3ba5b790-7087-474b-8c43-e61f881789b7"),
                            Comments = "The Football Is Good For Training And Recreational Purposes",
                            CostPrice = 13m,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Gostoso Madeira Camiseta",
                            QuantityInStock = 8,
                            SalePrice = 26m
                        },
                        new
                        {
                            Id = new Guid("0f68ada0-f344-45e5-8a91-2903320547a3"),
                            Comments = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            CostPrice = 11m,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Gostoso Fresco Bacon",
                            QuantityInStock = -1,
                            SalePrice = 22m
                        },
                        new
                        {
                            Id = new Guid("a4d99481-7d48-4e6c-9dd5-a4d7a9b934db"),
                            Comments = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            CostPrice = 12m,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Rústico Algodão Computador",
                            QuantityInStock = 8,
                            SalePrice = 24m
                        },
                        new
                        {
                            Id = new Guid("321fc52b-5f68-4713-970b-2bfd9ab7cc33"),
                            Comments = "The Football Is Good For Training And Recreational Purposes",
                            CostPrice = 14m,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Refinado Concreto Sabonete",
                            QuantityInStock = 4,
                            SalePrice = 28m
                        },
                        new
                        {
                            Id = new Guid("5153124f-7840-4173-9680-1133c54adbf8"),
                            Comments = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            CostPrice = 15m,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sem marca Borracha Teclado",
                            QuantityInStock = -1,
                            SalePrice = 30m
                        },
                        new
                        {
                            Id = new Guid("fc867e41-6dc4-4d8a-95e4-6a48d91bd172"),
                            Comments = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            CostPrice = 8m,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Feito à mão Granito Chapéu",
                            QuantityInStock = 1,
                            SalePrice = 16m
                        },
                        new
                        {
                            Id = new Guid("3d14b010-ae0b-45e3-b399-b1f25d956341"),
                            Comments = "The Football Is Good For Training And Recreational Purposes",
                            CostPrice = 14m,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Incrível Congelado Computador",
                            QuantityInStock = 6,
                            SalePrice = 28m
                        },
                        new
                        {
                            Id = new Guid("be36be74-d90f-45c4-afe9-01512b702535"),
                            Comments = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            CostPrice = 7m,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Pequeno Fresco Sapatos",
                            QuantityInStock = 8,
                            SalePrice = 14m
                        },
                        new
                        {
                            Id = new Guid("38bf32a1-d51f-4a4b-b211-d95bc5d9bdd3"),
                            Comments = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            CostPrice = 10m,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Lindo Algodão Teclado",
                            QuantityInStock = 9,
                            SalePrice = 20m
                        },
                        new
                        {
                            Id = new Guid("3640637c-774f-4487-ad4d-2b6bb88f2140"),
                            Comments = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            CostPrice = 12m,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Incrível Madeira Sabonete",
                            QuantityInStock = 6,
                            SalePrice = 24m
                        },
                        new
                        {
                            Id = new Guid("ec7f9470-0fbf-4ff3-9ea2-534ba18d3078"),
                            Comments = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            CostPrice = 10m,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Feito à mão Aço Computador",
                            QuantityInStock = -1,
                            SalePrice = 20m
                        },
                        new
                        {
                            Id = new Guid("21c0b092-6384-4a08-b296-498db9352441"),
                            Comments = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            CostPrice = 10m,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Inteligente Borracha Salada",
                            QuantityInStock = 9,
                            SalePrice = 20m
                        },
                        new
                        {
                            Id = new Guid("41611875-0380-4b29-9fb7-2c9ba81f037a"),
                            Comments = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            CostPrice = 5m,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sem marca Concreto Peixe",
                            QuantityInStock = 3,
                            SalePrice = 10m
                        },
                        new
                        {
                            Id = new Guid("70def688-448e-4fb6-8396-45992e8b436e"),
                            Comments = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            CostPrice = 15m,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Refinado Madeira Cadeira",
                            QuantityInStock = 8,
                            SalePrice = 30m
                        },
                        new
                        {
                            Id = new Guid("2da4a307-749a-4c8d-9ec4-8920f2161de3"),
                            Comments = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            CostPrice = 12m,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Rústico Metal Atum",
                            QuantityInStock = 7,
                            SalePrice = 24m
                        });
                });

            modelBuilder.Entity("Optimus.Domain.Entities.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("InactivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("inactivated_at");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("password");

                    b.Property<int>("Profile")
                        .HasColumnType("integer")
                        .HasColumnName("profile");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("222bf5a6-ff6b-4506-a468-c2ecf0dbcba6"),
                            CreatedAt = new DateTime(2024, 5, 18, 19, 3, 45, 593, DateTimeKind.Utc).AddTicks(6633),
                            Email = "admin@optimus.com",
                            Password = "7110eda4d09e062aa5e4a390b0a572ac0d2c0220",
                            Profile = 0
                        },
                        new
                        {
                            Id = new Guid("a2d39575-4488-4a35-a97a-fe92abafbcf7"),
                            CreatedAt = new DateTime(2024, 5, 18, 19, 3, 45, 593, DateTimeKind.Utc).AddTicks(6653),
                            Email = "operador@optimus.com",
                            Password = "7110eda4d09e062aa5e4a390b0a572ac0d2c0220",
                            Profile = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
